set -s escape-time 0

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set-option -g set-clipboard on

set -s extended-keys off
set -as terminal-features 'xterm*:extkeys'
set -g xterm-keys on

set -g base-index 1
set -g pane-base-index 1
set -g mouse on

bind r source-file ~/.tmux.conf

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
