set -s escape-time 0

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set-option -g set-clipboard on

set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
set-window-option -g xterm-keys on
set -s extended-keys off
set -as terminal-features 'xterm*:extkeys'

set -g base-index 1
set -g pane-base-index 1
set -g mouse on

bind r source-file ~/.tmux.conf

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key -n C-1 send-keys "\e[49;5u"
bind-key -n C-2 send-keys "\e[50;5u"
bind-key -n C-3 send-keys "\e[51;5u"
bind-key -n C-4 send-keys "\e[52;5u"
bind-key -n C-5 send-keys "\e[53;5u"
bind-key -n C-6 send-keys "\e[54;5u"
bind-key -n C-7 send-keys "\e[55;5u"
bind-key -n C-8 send-keys "\e[56;5u"
bind-key -n C-9 send-keys "\e[57;5u"
bind-key -n C-0 send-keys "\e[48;5u"
