set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"

set -g status-bg black
set -g status-fg white

set -s escape-time 0

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g base-index 1
set -g pane-base-index 1
set -g mouse on

bind r source-file ~/.tmux.conf

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

unbind C-1
unbind C-2
unbind C-3
unbind C-4
unbind C-5
unbind C-6
unbind C-7
unbind C-8
unbind C-9
unbind C-0
