set noerrorbells
set nowrap
set nu
set rnu
set encoding=utf-8
set cursorline
set showmatch
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smartindent
set smartcase
set undodir=~/.vim/undodir
set undofile
set incsearch
set colorcolumn=0
set noruler
set noshowmode
set hidden
set nohlsearch
set nobackup
set nowb
set noswapfile
set termguicolors
set updatetime=100
